<a href="https://colab.research.google.com/github/rafaelminski/java/blob/main/NumpyManipulacao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
a = np.array([5,6,8])

In [5]:
print(a)

[5 6 8]


In [17]:
arr = np.arange(12)
print(arr)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)


In [19]:
arr=  arr.reshape((4,3))
print(arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [20]:
arr = np.arange(27)

In [21]:
arr.reshape((3,3,3))

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [24]:
np.full((10,8), '🤣')

array([['🤣', '🤣', '🤣', '🤣', '🤣', '🤣', '🤣', '🤣'],
       ['🤣', '🤣', '🤣', '🤣', '🤣', '🤣', '🤣', '🤣'],
       ['🤣', '🤣', '🤣', '🤣', '🤣', '🤣', '🤣', '🤣'],
       ['🤣', '🤣', '🤣', '🤣', '🤣', '🤣', '🤣', '🤣'],
       ['🤣', '🤣', '🤣', '🤣', '🤣', '🤣', '🤣', '🤣'],
       ['🤣', '🤣', '🤣', '🤣', '🤣', '🤣', '🤣', '🤣'],
       ['🤣', '🤣', '🤣', '🤣', '🤣', '🤣', '🤣', '🤣'],
       ['🤣', '🤣', '🤣', '🤣', '🤣', '🤣', '🤣', '🤣'],
       ['🤣', '🤣', '🤣', '🤣', '🤣', '🤣', '🤣', '🤣'],
       ['🤣', '🤣', '🤣', '🤣', '🤣', '🤣', '🤣', '🤣']], dtype='<U1')

In [28]:
arr = np.arange(25).reshape((5,5))
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [29]:
arr[1:3, 1:]

array([[ 6,  7,  8,  9],
       [11, 12, 13, 14]])

In [30]:
arr_x = np.arange(10).reshape(5,2)
arr_y = np.arange(10,20).reshape(5,2)

In [31]:
print(arr_x)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [32]:
print(arr_y)

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [33]:
print(arr_x+arr_y)

[[10 12]
 [14 16]
 [18 20]
 [22 24]
 [26 28]]


In [34]:
a = np.arange(25).reshape((5,5))
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [36]:
idx = a > 8
print(idx)

[[False False False False False]
 [False False False False  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [37]:
a[idx]

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
print(arr_x[1:4])

[[2 3]
 [4 5]
 [6 7]]


In [41]:
arr[arr>8]

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
arr[arr>8].sum()

264

In [43]:
arr%2==0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [44]:
arr[arr%2==0].sum()

156